### ISSUE TITLE
KeyError: 'Adafactor is already registered in optimizer at torch.optim'

### ISSUE THREAD

**Issue by Alohomora0130** [GrokCV/HazyDet#14]
(HazyDet) daoep@ubuntu-DSS8440:~/cjy/MyProject/HazyDet-master/HazyDet-master$ python tools/train_det.py configs/DeCoDet/DeCoDet_r50_1x_hazydet.py
Traceback (most recent call last):
  File "/home/daoep/cjy/MyProject/HazyDet-master/HazyDet-master/tools/train_det.py", line 10, in <module>
    from mmengine.runner import Runner
  File "/home/daoep/anaconda3/envs/HazyDet/lib/python3.9/site-packages/mmengine/runner/__init__.py", line 2, in <module>
    from ._flexible_runner import FlexibleRunner
  File "/home/daoep/anaconda3/envs/HazyDet/lib/python3.9/site-packages/mmengine/runner/_flexible_runner.py", line 14, in <module>
    from mmengine._strategy import BaseStrategy
  File "/home/daoep/anaconda3/envs/HazyDet/lib/python3.9/site-packages/mmengine/_strategy/__init__.py", line 4, in <module>
    from .base import BaseStrategy
  File "/home/daoep/anaconda3/envs/HazyDet/lib/python3.9/site-packages/mmengine/_strategy/base.py", line 19, in <module>
    from mmengine.model.wrappers import is_model_wrapper
  File "/home/daoep/anaconda3/envs/HazyDet/lib/python3.9/site-packages/mmengine/model/__init__.py", line 6, in <module>
    from .base_model import BaseDataPreprocessor, BaseModel, ImgDataPreprocessor
  File "/home/daoep/anaconda3/envs/HazyDet/lib/python3.9/site-packages/mmengine/model/base_model/__init__.py", line 2, in <module>
    from .base_model import BaseModel
  File "/home/daoep/anaconda3/envs/HazyDet/lib/python3.9/site-packages/mmengine/model/base_model/base_model.py", line 9, in <module>
    from mmengine.optim import OptimWrapper
  File "/home/daoep/anaconda3/envs/HazyDet/lib/python3.9/site-packages/mmengine/optim/__init__.py", line 2, in <module>
    from .optimizer import (OPTIM_WRAPPER_CONSTRUCTORS, OPTIMIZERS,
  File "/home/daoep/anaconda3/envs/HazyDet/lib/python3.9/site-packages/mmengine/optim/optimizer/__init__.py", line 5, in <module>
    from .builder import (OPTIM_WRAPPER_CONSTRUCTORS, OPTIMIZERS,
  File "/home/daoep/anaconda3/envs/HazyDet/lib/python3.9/site-packages/mmengine/optim/optimizer/builder.py", line 174, in <module>
    TRANSFORMERS_OPTIMIZERS = register_transformers_optimizers()
  File "/home/daoep/anaconda3/envs/HazyDet/lib/python3.9/site-packages/mmengine/optim/optimizer/builder.py", line 169, in register_transformers_optimizers
    OPTIMIZERS.register_module(name='Adafactor', module=Adafactor)
  File "/home/daoep/anaconda3/envs/HazyDet/lib/python3.9/site-packages/mmengine/registry/registry.py", line 661, in register_module
    self._register_module(module=module, module_name=name, force=force)
  File "/home/daoep/anaconda3/envs/HazyDet/lib/python3.9/site-packages/mmengine/registry/registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'Adafactor is already registered in optimizer at torch.optim'
出现上面的问题，想请问一下是什么情况，应该怎么办？谢谢！

**Comment by ironmanfcf** [comment]
I have not encountered the above situation and suspect that the error is caused by version conflicts and incompatibility in the environment.
